language: node_js
node_js:
- '0.10'
env:
  global:
  #FTP_HOST
  - secure: H3HBo1I1cD8y4P+33YaN4i5G+tLwmf8VEu9H6G/QE4rSVf6LWOKygul9CYNI8g4As4UMlJww8xwG4fuwXT0+LJAS+tmi49WQ+Nkt5Tq1B0ocUqC9qg4GfwISrEFkkJ85P1TkniAMA5OILQl0eAfzsMMbpL1Mlozt2TwusI96wss=
  #FTP_USER
  - secure: TaLoipF/SNIQQbjnVRrI0361oi6yLrAio+ilnmC2kcduz/U9XO6NCC43Ip5g4H5m8N0nR+FMjboGXPfS/QETnrL0PSouyrIaLT+/hJes2nOtY5+3fry5BqbsT6ab98hJx70T//mzNxVFa30BD+pMLeqDVtcMvFAZRCb6yGOf2r4=
  #FTP_PASS
  - secure: GR7dRyEnHu9mMtw9v5sm3xAO/p5SWTjWFZfJ+aVPASMdkngX4NxFRKcSl7LRfVNRCPaohsAdeGCJzbi8rDah/4OqFZchRfGU3zD+vRuNW3yLBeSIDsXdG9qwXe/z/wKEUjD8Qd5hsvq3w3TusgUPULnQ/ftFCfrLCaKcQCBpCpM=
  #HOSTROOT
  - secure: QL0mbmKovNgTKYe4iBDVTPZkPNsrZekfhZv2r6I0j3YGWxShMwGb5Bd+R9FHO0Q7cLmNJz7Fr6HTGDIIMbzM6MmbG68eijY085OT+NPXQ63RLGKXOZGIzq8zATCvE2frWo+eVnahGKLtTyKozF9UrRzuoDKgBUVR2cxU1cvLVBo=
install:
- sudo apt-get install wput
- npm install
script:
- docpad generate --env static
after_success:
- wput out ftp://$FTP_USER:$FTP_PASS@$FTP_HOST/ --less-verbose --reupload --dont-continue
  --basename=out/ | sed "s/=>.*:21//"
